# Generated by Django 4.2.4 on 2023-08-06 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("REC", "Records"),
                    ("CL", "Clothing"),
                    ("PT", "Posters"),
                    ("MC", "Miscellaneous"),
                ],
                default="",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(
                blank=True,
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2023),
                ],
            ),
            preserve_default=False,
        ),
    ]
